### ISSUE TITLE
When deselecting ALL button, irrelevant aircraft will start to display

### ISSUE THREAD

**Issue by dsolesvik** [vNAAATS/vNAAATS-net#5]
TTSIA; before ALL, its fine, ALL displays everyone, turning ALL off will only hide half of the aircraft. There will still be a lot of irrelevant aircraft on the scope. 
![image](https://user-images.githubusercontent.com/56816890/133479930-e6cf1d7b-a859-4e0c-abaf-dbf3e2822e7e.png)

**Comment by aogden41** [comment]
wrong repository

this one instead https://github.com/vNAAATS/vatsim-NAAATS
